name: Sample workflow for Firebase Distribution action
on: [push, pull_request, workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get sample .apk for test purposes
        run: wget https://github.com/appium/appium/raw/1.10/sample-code/apps/ApiDemos-debug.apk
      - name: Upload artifact to Firebase Distribution
        uses: ./
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: Testers
          file: ApiDemos-debug.apk
      - name: Upload artifact to Firebase Distribution with bullet points release notes
        uses: ./
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: Testers
          releaseNotes: |
            - Empty state for no data
            - Error report view
            - Minor updates on the crash report
          file: ApiDemos-debug.apk

